name: features_github_repository
description: "This package provides features for GitHub repository."
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.3.1
  flutter: ^3.19.3

dependencies:
  cores_data:
    path: ../../cores/data
  cores_designsystem:
    path: ../../cores/designsystem
  cores_navigation:
    path: ../../cores/navigation
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  freezed_annotation: ^2.4.1
  hooks_riverpod: ^2.4.9
  json_annotation: ^4.8.1
  riverpod_annotation: ^2.3.3

dev_dependencies:
  build_runner: ^2.4.7
  custom_lint: ^0.5.11
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  riverpod_generator: ^2.3.9
  riverpod_lint: ^2.3.7
  yumemi_lints: ^1.3.0
